### ISSUE TITLE
What framework did you use for the game?

### ISSUE THREAD

**Issue by liconaj** [Sheepolution/prove-thine-worth#1]
Hi, I hope you are well. I have discovered this wonderful game recently and have been fascinated by it. Actually, I would like to know a little bit more about the framework that you used to develope the game (is it rxi/juno?) and how you created the binary files. Is it possible? Thanks!

**Comment by Sheepolution** [comment]
Hi. This game was made with Cade, an unfinished project by rxi. I got access to the beta version to play around with it, and eventually made this game. Sadly, rxi decided to cancel cade and so it has never been released. If you want to have a similar experience I recommend Pico-8.
